# Generated by Django 4.1.7 on 2023-08-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_name', models.CharField(max_length=150)),
                ('founder_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
