# Generated by Django 4.1.7 on 2023-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.UUIDField()),
                ('startup_name', models.CharField(max_length=150)),
                ('founder_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to say')], default='Male', max_length=20)),
                ('qualifications', models.CharField(max_length=120)),
                ('contact_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('institution_attended', models.CharField(blank=True, max_length=120, null=True)),
                ('founders_experience', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=120, null=True)),
                ('brief_description', models.TextField()),
                ('incorporation_date', models.DateField()),
                ('incorporation_certificate', models.FileField(default=None, max_length=300, null=True, upload_to='incorp_cert/')),
                ('website', models.URLField(max_length=300)),
                ('address_of_company', models.TextField()),
                ('company_sector', models.CharField(max_length=400)),
                ('technology_area', models.CharField(max_length=300)),
                ('company_stage', models.CharField(choices=[('Ideation', 'Ideation'), ('MVP', 'Minimum Viable Product (MVP)'), ('Product-Market-Fit', 'Product-Market-Fit'), ('Growth', 'Growth')], default='Ideation', max_length=120)),
                ('target_market', models.TextField()),
                ('usp', models.TextField()),
                ('revenue_streams', models.TextField()),
                ('pitchdeck', models.FileField(default=None, max_length=300, null=True, upload_to='pitchdeck/')),
            ],
        ),
    ]
