# Generated by Django 4.1.7 on 2023-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to say')], max_length=20),
        ),
    ]
