# Generated by Django 4.1.7 on 2023-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_isaccepted_alter_application_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='infoVerified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_stage',
            field=models.CharField(choices=[('Ideation', 'Ideation'), ('Proof of Concept', 'Proof of Concept'), ('Prototype Development', 'Prototype Development'), ('MVP', 'Minimum Viable Product (MVP)'), ('In Market', 'In Market'), ('Product-Market-Fit', 'Product-Market-Fit'), ('Growth', 'Growth')], max_length=120),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_number',
            field=models.BigIntegerField(help_text="<span class='form-text text-muted'><small>Please enter the number without +91</small></span>"),
        ),
        migrations.AlterField(
            model_name='application',
            name='email_id',
            field=models.EmailField(help_text="<span class='form-text text-muted'><small>This Email will be used for further communications</small></span>", max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='founder_name',
            field=models.CharField(help_text="<span class='form-text text-muted'><small>Please enter name without honorific such as Mr./Ms.</small></span>", max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='incorporation_certificate',
            field=models.FileField(blank=True, default=None, help_text="<span class='form-text text-muted'><small>Please upload pdf file of size less than 200KB</small></span>", max_length=300, null=True, upload_to='incorp_cert/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='incorporation_date',
            field=models.DateField(help_text="<span class='form-text text-muted'><small>Please enter date in yyyy-mm-dd format</small></span>"),
        ),
        migrations.AlterField(
            model_name='application',
            name='pitchdeck',
            field=models.FileField(blank=True, default=None, help_text="<span class='form-text text-muted'><small>Please upload pdf file of size less than 200KB</small></span>", max_length=300, null=True, upload_to='pitchdeck/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='revenue_streams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(help_text="<span class='form-text text-muted'><small>Please enter your website full url</small></span>", max_length=300),
        ),
    ]
