# Generated by Django 4.1.7 on 2023-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application_infoverified_application_isrejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_stage',
            field=models.CharField(choices=[('Submission', 'Submission'), ('Under Review', 'Under Review'), ('Verification', 'Verification'), ('Onboarding', 'Onboarding')], default='Submission', max_length=80),
        ),
    ]
